version: "3"
services:
  my5grantester:
    build:
      context: ./
    privileged: true
    command: bash -c "apt update && apt install -y iproute2 && ./app ${TEST_PARAMETERS}"
    volumes:
      - ./config/tester.yaml:/workspace/my5G-RANTester/config/config.yml
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - tester.free5gc.org

  iperf:
    image: mlabbe/iperf:latest
    container_name: iperf
    ports:
      - 5001:5001
    command: -s
    networks:
      default:
        aliases:
          - iperf.free5gc.org

networks:
  default:
    external: true
    name: "free5gc-compose_default"
  metrics_net:
    external: true
    name: coletordemetricas-dockerstats_coleta
